name = "cfwaibot"
main = "src/index.ts"
compatibility_date = "2025-01-29"
workers_dev = false

[observability]
enabled = true

[[routes]]
pattern = "cfwaibot.incbx.us.kg"
custom_domain = true

[ai]
binding = "AI"
