name = "cfwaibot"
main = "src/index.ts"
compatibility_date = "2025-01-29"
workers_dev = false

[observability]
enabled = true

[[routes]]
pattern = "cfwaibot.incbx.us.kg"
custom_domain = true

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SESSION_STORE"
id = "3b1982ac317441ca8dd7dd8d38a3bc69"
